// frontend/src/App.vue
<template>
  <router-view />
</template>

<script lang="ts" setup>
import { onMounted } from 'vue'
import { useRouter } from 'vue-router'
import { getSession } from '@/api/auth'

const router = useRouter()

onMounted(async () => {
  const session = await getSession()
  if (!session) {
    router.push('/login')
  } else {
    switch (session.role) {
      case 'admin':
        router.push('/admin/dashboard')
        break
      case 'doctor':
        router.push('/doctor/dashboard')
        break
      case 'patient':
        router.push('/patient/dashboard')
        break
    }
  }
})
</script>

// frontend/src/app/page.tsx
'use client';

import { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation'; 
import { jwtDecode } from 'jwt-decode';
import Spinner from './pages'; 

interface TokenPayload {
  sub: string;
  role: string;
  exp: number;
}

export default function Home() {
  const router = useRouter();
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const token = localStorage.getItem('access_token');
    if (!token) {
      router.replace('/pages/auth/login');
      return;
    }

    try {
      const decoded = jwtDecode<TokenPayload>(token);

      if (decoded.exp * 1000 < Date.now()) {
        localStorage.removeItem('access_token');
        router.replace('/login');
        return;
      }

      switch (decoded.role) {
        case 'admin':
          router.replace('/admin/dashboard');
          break;
        case 'doctor':
          router.replace('/doctor/dashboard');
          break;
        case 'patient':
          router.replace('/patient/dashboard');
          break;
        default:
          router.replace('/login');
      }
    } catch (error) {
      localStorage.removeItem('access_token');
      router.replace('/login');
    } finally {
      setLoading(false);
    }
  }, [router]);

  return <>{loading && <Spinner />}</>;
}
